<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta content="width=device-width, initial-scale=1.0" name="viewport">

	<title>Carbon Footprint Calculator</title>

	<!-- Favicons -->
	<link href="assets/img/" rel="icon">

	<!-- Google Fonts -->
	<link
		href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
		rel="stylesheet">

	<!-- Template Main CSS File -->
	<link href="assets/css/style.css" rel="stylesheet">
	<?php 
    include 'header.php'; 
    ?>
</head>

<body>


	<!-- ======= Hero Section ======= -->
	<section id="hero">
		<div id="heroCarousel" data-bs-interval="5000" class="carousel slide carousel-fade" data-bs-ride="carousel">

			<ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

			<div class="carousel-inner" role="listbox">

				<!-- Slide 1 -->
				<div class="carousel-item active" style="background-image: url(assets/img/slide/slide-1.jpg)">
					<div class="carousel-container">
						<div class="container">
							<h2 class="animate__animated animate__fadeInDown">Welcome to <span>CarboNeutral</span></h2>
							<p class="animate__animated animate__fadeInUp">
								CarboNeutral helps you calculate your carbon emissions and helps you reduce them by providing personalised suggestions based on the assessments.
							</p>
							<a href="calculator.php"
								class="btn-get-started animate__animated animate__fadeInUp scrollto">Calculate</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section><!-- End Hero -->
	<br>
	<hr>

	<main id="main">


		<!-- ======= services Section ======= -->
		<section id="services" class="services">
			<div class="container">
				<div class="section-title">
					<h2>Factors considered</h2>
				</div>

				<div class="row no-gutters">

					<div class="col-lg-4 col-md-6 content-item">
						<span>01</span>
						<h4>Transportation</h4>
						<p>This includes fuel consumption by vehicles owned or leased by the business, as well as
							employee commuting.</p>
					</div>

					<div class="col-lg-4 col-md-6 content-item">
						<span>02</span>
						<h4>Waste management</h4>
						<p>This includes the disposal of waste produced by the business, including recycling and
							composting.</p>
					</div>

					<div class="col-lg-4 col-md-6 content-item">
						<span>03</span>
						<h4> Water usage</h4>
						<p>This includes both the direct and indirect water usage of the business, such as water used
							for manufacturing and processing.</p>
					</div>

					<div class="col-lg-4 col-md-6 content-item">
						<span>04</span>
						<h4>Supply chain</h4>
						<p>This includes the greenhouse gas emissions generated by the production and transportation of
							goods and services purchased by the business.</p>
					</div>

					<div class="col-lg-4 col-md-6 content-item">
						<span>05</span>
						<h4>Building materials</h4>
						<p>This includes the emissions associated with the extraction, production, materials used in the
							construction and maintenance of the infrastructure</p>
					</div>

					<div class="col-lg-4 col-md-6 content-item">
						<span>06</span>
						<h4>Energy usage</h4>
						<p>This includes electricity usage and any other forms of energy consumption, such as heating
							and cooling.
						</p>
					</div>

				</div>

			</div>
		</section><!-- End Why Us Section -->
		<br>

		<section id="cta" class="cta">
			<div class="container">
				<div class="row">
				<?php
					if (isset($_SESSION['user_id'])) {
						echo '<div class="col-lg-9 text-center text-lg-start">
						<h3>Calculate your carbon footprint</h3>
						<p>Calculate your carbon footprint and know how much you are contributing to global warming.</p>
					</div>
					';
					}
					else {
						echo '
						<div class="col-lg-9 text-center text-lg-start">
							<h3>Assesments</h3>
							<p>
								Try out our assesments and know how much you are contributing to global warming.
							</p>
						</div>
						<div class="col-lg-3 cta-btn-container text-center">
							<button type="button" class="btn btn-outline-light px-3" data-bs-toggle="modal"
								data-bs-target="#loginModal">
								Login
							</button>
						</div>
					';
					}
				?>
				</div>
			</div>
		</section>


		<!-- ======= Contact Section ======= -->
		<section id="contact" class="contact">
			<div class="container">

				<div class="section-title">
					<h2>Contact</h2>
				</div>

				<div class="row">

					<div class="col-lg-5 d-flex align-items-stretch">
						<div class="info">
							<div class="address">
								<i class="bi bi-geo-alt"></i>
								<h4>Location:</h4>
								<p>VESIT, Chembur</p>
							</div>
							<iframe
								src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3771.4188772513444!2d72.8867648501286!3d19.04531225782305!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7c8add9569a29%3A0xb7ad04bf9a389df7!2sVivekanand%20Education%20Society&#39;s%20Institute%20Of%20Technology%20(VESIT)!5e0!3m2!1sen!2sin!4v1678425895301!5m2!1sen!2sin"
								width="400" height="500" style="border:0;" allowfullscreen="" loading="lazy"
								referrerpolicy="no-referrer-when-downgrade"></iframe>
						</div>
					</div> 
					<div class="col-lg-7 mt-5 mt-lg-0 d-flex align-items-stretch">
						<form action="forms/contact.php" method="post" role="form" class="php-email-form">
							<div class="row">
								<div class="form-group col-md-6">
									<label for="name">Your Name</label>
									<input type="text" name="name" class="form-control" id="name" required>
								</div>
								<div class="form-group col-md-6 mt-3 mt-md-0">
									<label for="email">Your Email</label>
									<input type="email" class="form-control" name="email" id="email" required>
								</div>
							</div>
							<div class="form-group mt-3">
								<label for="subject">Subject</label>
								<input type="text" class="form-control" name="subject" id="subject" required>
							</div>
							<div class="form-group mt-3">
								<label for="message">Message</label>
								<textarea class="form-control" name="message" rows="10" id="message" required></textarea>
							</div>
							<div class="my-3">
								<div class="loading">Loading</div>
								<div class="error-message"></div>
								<div class="sent-message">Your message has been sent. Thank you!</div>
							</div>
							<div class="text-center"><button type="submit">Send Message</button></div>
						</form>
					</div>

				</div>

			</div>
		</section><!-- End Contact Section -->

	</main><!-- End #main -->

	<?php
		include 'footer.php';
	?>

</body>

</html>
